services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: stanley
      POSTGRES_PASSWORD: stanley
      POSTGRES_DB: finance_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Adminer GUI Service
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata: